version: '3'
services:

  php:
    build:
      context: .
      dockerfile: build/php.Dockerfile
    networks:
      - lamp-network

#  nginx:
#    build:
#      context: .
#      dockerfile: build/nginx.Dockerfile
#    ports:
#      - "8080:80"
#    volumes:
#      - ./html:/var/www/html
#    networks:
#      - lamp-network

#  mariadb:
#    build:
#      context: .
#      dockerfile: build/mariadb.Dockerfile
#    environment:
#      MYSQL_ROOT_PASSWORD: mysecret
#    volumes:
#      - mariadb_data:/var/lib/mysql
#    networks:
#      - lamp-network

  phpmyadmin:
    build:
      context: .
      dockerfile: build/phpmyadmin.Dockerfile
    ports:
      - "8181:8080"
    environment:
      PMA_HOST: mariadb
    networks:
      - lamp-network

networks:
  lamp-network:
    driver: bridge

volumes:
  mariadb_data:
